import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-coupon-credit',
  standalone: true,
  imports: [RouterModule],
  template: `
    <div class="page">
      <a routerLink="/smart-hr" class="back-link">
        <i class="bi bi-arrow-left"></i> Smart HR
      </a>
      <h1>Coupon &amp; Credit System</h1>
      <p class="subtitle">Credit-based licensing system for Smart HR &mdash; coupon generation, distribution, redemption, and balance tracking across platform control and subscription pages.</p>
      <div class="doc-status"><i class="bi bi-check-circle-fill"></i> Completed</div>

      <!-- Overview -->
      <section class="card">
        <h2>Overview</h2>
        <p>Smart HR uses a credit-based licensing model where companies purchase or redeem credits to maintain platform access. <strong>1 Credit = 1 Staff for Full Month Access.</strong></p>
        <p>The coupon system (<strong>CrdCoupon</strong>) manages license credits &mdash; generated by admin, redeemed by license owners to add credits to their account.</p>
        <h3>Key Features</h3>
        <ul>
          <li><strong>Generate Coupons</strong> &mdash; Batch generation with configurable credit count, expiry, and prefix</li>
          <li><strong>Send via Email</strong> &mdash; Email coupon codes directly to license owners</li>
          <li><strong>Apply to License</strong> &mdash; Redeem coupon codes to add credits to a license</li>
          <li><strong>Track Usage</strong> &mdash; Full audit trail of generation, redemption, and balance changes</li>
          <li><strong>Price Calculator</strong> &mdash; Staff count x month count x credit price with Myanmar market pricing</li>
        </ul>
      </section>

      <!-- Database Schema -->
      <section class="card">
        <h2>Database Schema</h2>

        <h3>Core Coupon Tables</h3>
        <div class="er-diagram">
          <div class="er-table">
            <div class="er-header">CrdCoupon</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> CouponId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">CouponCode <span class="type">nvarchar(50)</span></div>
            <div class="er-row">CreditCount <span class="type">int</span></div>
            <div class="er-row">CouponStatus <span class="type">nvarchar(20)</span></div>
            <div class="er-row">StartOn <span class="type">datetime</span></div>
            <div class="er-row">ExpiryOn <span class="type">datetime</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> UsedByLicense <span class="type">nvarchar(50)</span></div>
            <div class="er-row">UsedOn <span class="type">datetime</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> GenerateId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">CreditType <span class="type">nvarchar(20)</span></div>
            <div class="er-row">ValidationExpression <span class="type">nvarchar(200)</span></div>
            <div class="er-row">Active <span class="type">bit</span></div>
            <div class="er-row">CreatedBy / CreatedOn <span class="type">nvarchar / datetime</span></div>
          </div>
          <div class="er-relation">
            <span>N</span>
            <div class="er-line"></div>
            <span>1</span>
          </div>
          <div class="er-table">
            <div class="er-header">CrdCouponLog</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> GenerateId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">GenerateOn <span class="type">datetime</span></div>
            <div class="er-row">CreditType <span class="type">nvarchar(20)</span></div>
            <div class="er-row">CreditValue <span class="type">int</span></div>
            <div class="er-row">NoOfCoupon <span class="type">int</span></div>
            <div class="er-row">StartOn <span class="type">datetime</span></div>
            <div class="er-row">ExpiryOn <span class="type">datetime</span></div>
            <div class="er-row">Status <span class="type">nvarchar(20)</span></div>
            <div class="er-row">BaseCouponCode <span class="type">nvarchar(50)</span></div>
          </div>
        </div>

        <h3>Supporting Tables</h3>
        <div class="er-diagram">
          <div class="er-table">
            <div class="er-header">CrdCouponView</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> CouponId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">CouponCode <span class="type">nvarchar(50)</span></div>
            <div class="er-row">CreditCount <span class="type">int</span></div>
            <div class="er-row">CouponStatus <span class="type">nvarchar(20)</span></div>
            <div class="er-row">CompanyName <span class="type">nvarchar(200)</span></div>
            <div class="er-row">LicenseNo <span class="type">nvarchar(50)</span></div>
            <div class="er-row dim">(View: joins CrdCoupon + SysLicense)</div>
          </div>
          <div class="er-table">
            <div class="er-header">CrdCouponPrefix</div>
            <div class="er-row">CouponPrefix <span class="type">nvarchar(10)</span></div>
            <div class="er-row">CreditUnit <span class="type">int</span></div>
          </div>
        </div>

        <h3>Credit Balance Tables</h3>
        <div class="er-diagram">
          <div class="er-table">
            <div class="er-header">AicLicenseCredit</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> LicenseCreditId <span class="type">nvarchar(50)</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> LicenseId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">TotalCredits <span class="type">decimal</span></div>
            <div class="er-row">UsedCredits <span class="type">decimal</span></div>
            <div class="er-row">RemainingCredits <span class="type">decimal</span></div>
            <div class="er-row">CreditLimit <span class="type">decimal</span></div>
            <div class="er-row">MonthlyAllowance <span class="type">decimal</span></div>
            <div class="er-row">WarningThreshold <span class="type">decimal</span></div>
            <div class="er-row">CriticalThreshold <span class="type">decimal</span></div>
          </div>
          <div class="er-relation">
            <span>1</span>
            <div class="er-line"></div>
            <span>N</span>
          </div>
          <div class="er-table">
            <div class="er-header">AicCreditTransaction</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> TransactionId <span class="type">nvarchar(50)</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> LicenseCreditId <span class="type">nvarchar(50)</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> LicenseId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">TransactionType <span class="type">nvarchar(20)</span></div>
            <div class="er-row">Amount <span class="type">decimal</span></div>
            <div class="er-row">BalanceBefore <span class="type">decimal</span></div>
            <div class="er-row">BalanceAfter <span class="type">decimal</span></div>
            <div class="er-row">Description <span class="type">nvarchar(500)</span></div>
            <div class="er-row">ProcessedBy / ProcessedOn <span class="type">nvarchar / datetime</span></div>
          </div>
        </div>

        <h3>Credit Unit Tracking</h3>
        <div class="er-diagram">
          <div class="er-table">
            <div class="er-header">CrdCreditUnitAdd</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> CreditAddId <span class="type">nvarchar(50)</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> LicenseId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">AddedOn <span class="type">datetime</span></div>
            <div class="er-row">AddedCreditUnit <span class="type">int</span></div>
            <div class="er-row">RefType <span class="type">nvarchar(20)</span></div>
            <div class="er-row">RefTypeId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">Status <span class="type">nvarchar(20)</span></div>
          </div>
          <div class="er-table">
            <div class="er-header">CrdCreditUnitUsed</div>
            <div class="er-row pk"><span class="badge-pk">PK</span> CreditUsedId <span class="type">nvarchar(50)</span></div>
            <div class="er-row fk"><span class="badge-fk">FK</span> LicenseId <span class="type">nvarchar(50)</span></div>
            <div class="er-row">UsedOn <span class="type">datetime</span></div>
            <div class="er-row">UsedCreditUnit <span class="type">int</span></div>
            <div class="er-row">CreditValue <span class="type">decimal</span></div>
            <div class="er-row">UsedTitle <span class="type">nvarchar(200)</span></div>
            <div class="er-row">Status <span class="type">nvarchar(20)</span></div>
          </div>
        </div>
      </section>

      <!-- System Coupon Workflow -->
      <section class="card">
        <h2>System Coupon Workflow</h2>
        <div class="diagram">
          <div class="diagram-row">
            <div class="diagram-node node-start"><i class="bi bi-person-gear"></i> Admin Generates<small>Platform Control</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-action"><i class="bi bi-database"></i> CRD_CouponGenerate<small>Stored Procedure</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-pending"><i class="bi bi-ticket-perforated"></i> CrdCoupon Created<small>Status: Active</small></div>
          </div>
          <div class="diagram-down"><i class="bi bi-arrow-down"></i></div>
          <div class="diagram-row">
            <div class="diagram-node node-step"><i class="bi bi-envelope"></i> Send Email<small>(Optional)</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-action"><i class="bi bi-person-check"></i> License Owner<small>Applies Coupon Code</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-success"><i class="bi bi-plus-circle"></i> Credits Added<small>AicLicenseCredit</small></div>
          </div>
          <div class="diagram-down"><i class="bi bi-arrow-down"></i></div>
          <div class="diagram-row">
            <div class="diagram-node node-action"><i class="bi bi-journal-check"></i> Transaction Logged<small>AicCreditTransaction</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-danger"><i class="bi bi-box-arrow-right"></i> User Logged Out<small>Refresh License Data</small></div>
          </div>
        </div>
      </section>

      <!-- Credit Balance Flow -->
      <section class="card">
        <h2>Credit Balance Flow</h2>
        <div class="diagram">
          <div class="diagram-row">
            <div class="diagram-node node-start"><i class="bi bi-hdd"></i> Load from<small>localStorage</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-action"><i class="bi bi-globe"></i> Fetch Myanmar<small>Market Config</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-pending"><i class="bi bi-speedometer2"></i> Display Balance<small>Added / Used / Remaining</small></div>
          </div>
          <div class="diagram-down"><i class="bi bi-arrow-down"></i></div>
          <div class="diagram-row">
            <div class="diagram-node node-step"><i class="bi bi-input-cursor-text"></i> User Enters Coupon<small>Coupon Code Input</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-pending"><i class="bi bi-question-circle"></i> Confirmation<small>Dialog</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-action"><i class="bi bi-cloud-upload"></i> API Call<small>useCouponForLicense</small></div>
          </div>
          <div class="diagram-down"><i class="bi bi-arrow-down"></i></div>
          <div class="diagram-row">
            <div class="diagram-node node-success"><i class="bi bi-check-circle"></i> Success<small>Credits Updated</small></div>
            <div class="diagram-arrow"><i class="bi bi-arrow-right"></i></div>
            <div class="diagram-node node-danger"><i class="bi bi-box-arrow-right"></i> Logout &amp; Redirect<small>Refresh Session</small></div>
          </div>
        </div>
      </section>

      <!-- API Endpoints -->
      <section class="card">
        <h2>API Endpoints</h2>

        <h3>CrdCouponApi</h3>
        <table>
          <thead><tr><th>Method</th><th>Endpoint</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><span class="method-get">GET</span></td><td><code>/GetAll</code></td><td>Get all coupons</td></tr>
            <tr><td><span class="method-get">GET</span></td><td><code>/GetByID/&#123;id&#125;</code></td><td>Get coupon by ID</td></tr>
            <tr><td><span class="method-get">GET</span></td><td><code>/GetByLicenseID/&#123;licenseId&#125;</code></td><td>Get coupons for a license</td></tr>
            <tr><td><span class="method-post">POST</span></td><td><code>/Create</code></td><td>Create a single coupon</td></tr>
            <tr><td><span class="method-delete">DELETE</span></td><td><code>/Remove/&#123;id&#125;</code></td><td>Remove a coupon</td></tr>
            <tr><td><span class="method-post">POST</span></td><td><code>/GenerateCoupon</code></td><td>Batch generate coupons via stored procedure</td></tr>
            <tr><td><span class="method-post">POST</span></td><td><code>/SendCouponEmail</code></td><td>Send coupon code via email to license owner</td></tr>
            <tr><td><span class="method-post">POST</span></td><td><code>/UseCouponForLicense</code></td><td>Redeem coupon code and add credits to license</td></tr>
          </tbody>
        </table>

        <h3>CrdCouponLogApi</h3>
        <table>
          <thead><tr><th>Method</th><th>Endpoint</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><span class="method-get">GET</span></td><td><code>/GetAll</code></td><td>Get all coupon generation logs</td></tr>
            <tr><td><span class="method-get">GET</span></td><td><code>/GetByLicenseID/&#123;licenseId&#125;</code></td><td>Get generation logs for a license</td></tr>
          </tbody>
        </table>
      </section>

      <!-- File Structure -->
      <section class="card">
        <h2>File Structure</h2>

        <h3>Backend (.NET)</h3>
        <table>
          <thead><tr><th>Layer</th><th>File</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td>API</td><td><code>CrdCouponApi.cs</code></td><td>REST API controller for coupon endpoints</td></tr>
            <tr><td>API</td><td><code>CrdCouponLogApi.cs</code></td><td>REST API controller for coupon log endpoints</td></tr>
            <tr><td>DTO</td><td><code>CrdCouponDTO.cs</code></td><td>Data transfer objects for coupon operations</td></tr>
            <tr><td>Controller</td><td><code>CrdCouponController.cs</code></td><td>Business logic for coupon CRUD and redemption</td></tr>
            <tr><td>Controller</td><td><code>CrdCouponLogController.cs</code></td><td>Business logic for generation log queries</td></tr>
          </tbody>
        </table>

        <h3>Frontend (Angular)</h3>
        <table>
          <thead><tr><th>Type</th><th>File</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td>Service</td><td><code>crd-coupon.service.ts</code></td><td>HTTP service for CrdCouponApi</td></tr>
            <tr><td>Service</td><td><code>crd-coupon-log.service.ts</code></td><td>HTTP service for CrdCouponLogApi</td></tr>
            <tr><td>DTO</td><td><code>crd-coupon-dto.ts</code></td><td>TypeScript interfaces for coupon data</td></tr>
            <tr><td>Component</td><td><code>coupons.component.ts</code></td><td>Platform control coupons listing page</td></tr>
            <tr><td>Component</td><td><code>coupon-detail.component.ts</code></td><td>Individual coupon detail view</td></tr>
            <tr><td>Component</td><td><code>credit-balance-info.component.ts</code></td><td>Credit balance display and coupon redemption modal</td></tr>
          </tbody>
        </table>

        <h3>Database Models (.NET Entity)</h3>
        <table>
          <thead><tr><th>File</th><th>Table/View</th></tr></thead>
          <tbody>
            <tr><td><code>CrdCoupon.cs</code></td><td>CrdCoupon</td></tr>
            <tr><td><code>CrdCouponLog.cs</code></td><td>CrdCouponLog</td></tr>
            <tr><td><code>CrdCouponView.cs</code></td><td>CrdCouponView (SQL View)</td></tr>
            <tr><td><code>CrdCouponPrefix.cs</code></td><td>CrdCouponPrefix</td></tr>
            <tr><td><code>AicLicenseCredit.cs</code></td><td>AicLicenseCredit</td></tr>
            <tr><td><code>AicCreditTransaction.cs</code></td><td>AicCreditTransaction</td></tr>
            <tr><td><code>CrdCreditUnitAdd.cs</code></td><td>CrdCreditUnitAdd</td></tr>
            <tr><td><code>CrdCreditUnitUsed.cs</code></td><td>CrdCreditUnitUsed</td></tr>
          </tbody>
        </table>
      </section>

      <!-- Coupon Statuses -->
      <section class="card">
        <h2>Coupon Statuses</h2>
        <table>
          <thead><tr><th>Status</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><span class="status-badge status-pending">Pending</span></td><td>Coupon generated but not yet activated (before StartOn date)</td></tr>
            <tr><td><span class="status-badge status-active">Active</span></td><td>Coupon is valid and available for redemption</td></tr>
            <tr><td><span class="status-badge status-used">Used</span></td><td>Coupon has been redeemed and credits applied to a license</td></tr>
            <tr><td><span class="status-badge status-expired">Expired</span></td><td>Coupon passed its ExpiryOn date without being redeemed</td></tr>
            <tr><td><span class="status-badge status-cancelled">Cancelled</span></td><td>Coupon manually deactivated by admin</td></tr>
          </tbody>
        </table>
      </section>

      <!-- Credit Balance Component -->
      <section class="card">
        <h2>Credit Balance Component</h2>
        <p>The <code>credit-balance-info.component.ts</code> provides the credit balance display and coupon redemption UI used across subscription pages.</p>

        <h3>Display Fields</h3>
        <ul>
          <li><strong>creditAdded</strong> &mdash; Total credits added to the license (animated counter)</li>
          <li><strong>creditUsed</strong> &mdash; Total credits consumed by active staff</li>
          <li><strong>creditBalance</strong> &mdash; Remaining credits available (creditAdded - creditUsed)</li>
        </ul>

        <h3>Myanmar Market Pricing</h3>
        <p>Fetched from <code>SysConfig</code> API for Myanmar market configuration:</p>
        <ul>
          <li><strong>bankName</strong> &mdash; Bank name for payment transfers</li>
          <li><strong>accountName</strong> &mdash; Account holder name</li>
          <li><strong>accountNumber</strong> &mdash; Bank account number</li>
          <li><strong>branch</strong> &mdash; Bank branch information</li>
        </ul>

        <h3>Price Calculator</h3>
        <table>
          <thead><tr><th>Input</th><th>Range</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><code>staffCount</code></td><td>1 &ndash; 1000</td><td>Number of staff to license</td></tr>
            <tr><td><code>monthCount</code></td><td>1 &ndash; 24</td><td>Number of months</td></tr>
            <tr><td><code>creditPrice</code></td><td>From SysConfig</td><td>Price per credit unit</td></tr>
          </tbody>
        </table>
        <p><strong>Formula:</strong> <code>Total = staffCount x monthCount x creditPrice</code></p>

        <h3>Coupon Redemption</h3>
        <ol>
          <li>User enters coupon code in the input field</li>
          <li>Confirmation dialog appears with coupon details</li>
          <li>API call to <code>UseCouponForLicense</code> endpoint</li>
          <li>On success: 5-second wait timer before modal close</li>
          <li>User is logged out and redirected to refresh license data</li>
        </ol>

        <h3>localStorage Keys</h3>
        <table>
          <thead><tr><th>Key</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><code>_creditAdded</code></td><td>Cached total credits added</td></tr>
            <tr><td><code>_creditUsed</code></td><td>Cached total credits used</td></tr>
            <tr><td><code>_licenseNo</code></td><td>Current license number</td></tr>
            <tr><td><code>_CompanyName</code></td><td>Current company name</td></tr>
            <tr><td><code>_licenseId</code></td><td>Current license ID</td></tr>
          </tbody>
        </table>
      </section>

      <!-- Platform Control Pages -->
      <section class="card">
        <h2>Platform Control Pages</h2>

        <h3>Coupons List <code>/system/coupons</code></h3>
        <ul>
          <li><strong>Generate Coupon</strong> &mdash; Batch coupon generation with credit type, count, validity period</li>
          <li><strong>Send Email</strong> &mdash; Email coupon codes to license owners</li>
          <li><strong>Status Summary</strong> &mdash; Dashboard showing Used/Active percentages</li>
          <li><strong>Date Filtering</strong> &mdash; Filter coupons by generation date range</li>
          <li><strong>Excel Export</strong> &mdash; Export coupon list to Excel</li>
        </ul>

        <h3>License Detail <code>/system/licenses</code></h3>
        <ul>
          <li><strong>Use Coupon Panel</strong> &mdash; Apply coupon codes directly to a license</li>
          <li><strong>Review Information</strong> &mdash; License details, company info, credit balance</li>
          <li><strong>Staff List</strong> &mdash; Active staff under this license</li>
          <li><strong>Coupons Section</strong> &mdash; History of coupons applied to this license</li>
        </ul>

        <h3>My Subscription <code>/config-module/my-subscription</code></h3>
        <ul>
          <li><strong>Billing Credits</strong> &mdash; Current credit balance overview</li>
          <li><strong>Usage Forecast</strong> &mdash; Projected credit usage based on current staff count</li>
          <li><strong>Apply Coupons</strong> &mdash; Self-service coupon redemption</li>
          <li><strong>Credit Top Up History</strong> &mdash; Log of all credit additions</li>
          <li><strong>Credit Usage History</strong> &mdash; Log of all credit deductions</li>
        </ul>
      </section>

      <!-- Permissions -->
      <section class="card">
        <h2>Permissions</h2>
        <table>
          <thead><tr><th>Program</th><th>Actions</th></tr></thead>
          <tbody>
            <tr>
              <td><code>PGM-Coupons</code></td>
              <td>
                <span class="perm-badge perm-read">Read</span>
                <span class="perm-badge perm-create">Create</span>
                <span class="perm-badge perm-update">Update</span>
                <span class="perm-badge perm-delete">Delete</span>
              </td>
            </tr>
          </tbody>
        </table>
      </section>

      <!-- Doc Log -->
      <section class="card">
        <h2>Doc Log</h2>
        <table>
          <thead><tr><th>Date</th><th>Author</th><th>Change</th></tr></thead>
          <tbody>
            <tr><td>2026-03-27</td><td>Hein Htet Zaw</td><td>Initial documentation</td></tr>
          </tbody>
        </table>
      </section>
    </div>
  `,
  styles: [`
    .page { max-width: 900px; margin: 0 auto; }
    .back-link {
      font-size: 13px; color: #6c8cff; text-decoration: none;
      display: inline-flex; align-items: center; gap: 4px; margin-bottom: 12px;
    }
    .back-link:hover { text-decoration: underline; }
    h1 { font-size: 28px; font-weight: 700; color: #1a1f36; margin: 0 0 8px; }
    .subtitle { font-size: 15px; color: #666; margin: 0 0 28px; line-height: 1.5; }
    .doc-status {
      display: inline-flex; align-items: center; gap: 6px;
      font-size: 12px; font-weight: 600; padding: 4px 14px;
      border-radius: 20px; margin-bottom: 24px;
      background: #e8f5e9; color: #43a047;
    }

    .card {
      background: #fff; border-radius: 14px; padding: 28px 32px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.06); margin-bottom: 16px;
    }
    .card h2 {
      font-size: 20px; font-weight: 700; color: #1a1f36; margin: 0 0 16px;
      padding-bottom: 10px; border-bottom: 2px solid #f0f0f0;
    }
    .card h3 { font-size: 16px; font-weight: 600; color: #1a1f36; margin: 20px 0 8px; }
    .card h4 { font-size: 14px; font-weight: 600; color: #555; margin: 16px 0 6px; }
    .card p { font-size: 14px; line-height: 1.7; color: #444; margin: 0 0 12px; }
    .card ul, .card ol { padding-left: 22px; margin: 0 0 12px; font-size: 14px; color: #444; }
    .card li { margin-bottom: 4px; line-height: 1.6; }

    code {
      background: #f0f3ff; color: #4a6cf7; padding: 2px 7px;
      border-radius: 4px; font-size: 13px;
    }
    pre {
      background: #1a1f36; border-radius: 10px; padding: 18px 22px;
      overflow-x: auto; margin: 0 0 14px;
    }
    pre code {
      background: none; color: #e0e6ff; padding: 0;
      font-size: 13px; line-height: 1.6; white-space: pre;
    }

    table {
      width: 100%; border-collapse: collapse; margin: 0 0 14px; font-size: 13px;
    }
    th {
      text-align: left; padding: 10px 12px; background: #f5f7fa;
      border-bottom: 2px solid #e0e4ec; font-weight: 600; color: #444;
    }
    td { padding: 9px 12px; border-bottom: 1px solid #f0f0f0; color: #444; }
    tr:hover td { background: #fafbfd; }

    strong { color: #1a1f36; }

    /* ER Diagram */
    .er-diagram {
      display: flex; align-items: flex-start; gap: 16px;
      flex-wrap: wrap; justify-content: center; padding: 12px 0;
    }
    .er-table {
      border: 2px solid #e0e4ec; border-radius: 10px; overflow: hidden;
      min-width: 220px; background: #fff;
    }
    .er-header {
      background: #1a1f36; color: #fff; padding: 10px 14px;
      font-weight: 700; font-size: 13px; text-align: center;
    }
    .er-row {
      padding: 6px 14px; font-size: 12px; color: #444;
      border-bottom: 1px solid #f0f0f0;
      display: flex; align-items: center; gap: 6px;
    }
    .er-row.pk { background: #f0f6ff; }
    .er-row.fk { background: #f5f0ff; }
    .er-row.dim { background: #f9f9f9; color: #999; font-style: italic; font-size: 11px; }
    .er-row .type { margin-left: auto; color: #999; font-size: 11px; }
    .badge-pk {
      background: #f9a825; color: #fff; padding: 1px 5px;
      border-radius: 3px; font-size: 10px; font-weight: 700;
    }
    .badge-fk {
      background: #7c4dff; color: #fff; padding: 1px 5px;
      border-radius: 3px; font-size: 10px; font-weight: 700;
    }
    .er-relation {
      display: flex; align-items: center; gap: 6px;
      font-size: 13px; font-weight: 700; color: #6c8cff;
      align-self: center;
    }
    .er-line {
      width: 40px; height: 2px; background: #6c8cff;
      position: relative;
    }
    .er-line::after {
      content: ''; position: absolute; right: -4px; top: -4px;
      border: 5px solid transparent; border-left: 6px solid #6c8cff;
    }

    /* Flow Diagram */
    .diagram { padding: 8px 0; }
    .diagram-row {
      display: flex; align-items: center; gap: 10px;
      flex-wrap: wrap; justify-content: center;
    }
    .diagram-node {
      display: flex; flex-direction: column; align-items: center; gap: 6px;
      padding: 14px 18px; border-radius: 12px; min-width: 110px;
      text-align: center; font-size: 13px; font-weight: 500;
    }
    .diagram-node i { font-size: 22px; }
    .diagram-node small { font-weight: 400; color: rgba(255,255,255,0.7); font-size: 11px; }
    .node-start { background: #e8ecf1; color: #555; }
    .node-start small { color: #888; }
    .node-action { background: #6c8cff; color: #fff; }
    .node-pending { background: #f9a825; color: #fff; }
    .node-step { background: #f0f3ff; color: #1a1f36; border: 2px solid #d0d8ff; }
    .node-step small { color: #888; }
    .node-success { background: #43a047; color: #fff; }
    .node-danger { background: #e53935; color: #fff; }
    .diagram-arrow { color: #bbb; font-size: 18px; }
    .diagram-down { text-align: center; color: #bbb; font-size: 20px; padding: 6px 0; }
    @media (max-width: 768px) {
      .diagram-row { flex-direction: column; gap: 0; }
      .diagram-arrow { transform: rotate(90deg); }
    }

    /* HTTP Method Badges */
    .method-get {
      background: #e8f5e9; color: #2e7d32; padding: 2px 8px;
      border-radius: 4px; font-size: 11px; font-weight: 700;
    }
    .method-post {
      background: #fff3e0; color: #e65100; padding: 2px 8px;
      border-radius: 4px; font-size: 11px; font-weight: 700;
    }
    .method-delete {
      background: #ffebee; color: #c62828; padding: 2px 8px;
      border-radius: 4px; font-size: 11px; font-weight: 700;
    }

    /* Status Badges */
    .status-badge {
      display: inline-block; padding: 3px 10px; border-radius: 4px;
      font-size: 12px; font-weight: 600;
    }
    .status-pending { background: #fff3e0; color: #e65100; }
    .status-active { background: #e8f5e9; color: #2e7d32; }
    .status-used { background: #e3f2fd; color: #1565c0; }
    .status-expired { background: #f3e5f5; color: #7b1fa2; }
    .status-cancelled { background: #ffebee; color: #c62828; }

    /* Permission Badges */
    .perm-badge {
      display: inline-block; padding: 3px 10px; border-radius: 4px;
      font-size: 11px; font-weight: 600; margin-right: 6px;
    }
    .perm-read { background: #e3f2fd; color: #1565c0; }
    .perm-create { background: #e8f5e9; color: #2e7d32; }
    .perm-update { background: #fff3e0; color: #e65100; }
    .perm-delete { background: #ffebee; color: #c62828; }
  `]
})
export class CouponCreditComponent {}
